sudo: false
language: python
python:
  - 2.7
cache:
  directories:
    - $HOME/.cache/pip
env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from
addons:
  apt:
    packages:
    - libhdf5-serial-dev
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=2.7
  - conda install --yes -n condaenv pip
  - source activate condaenv
install:
 - conda install --yes python=$TRAVIS_PYTHON_VERSION pandas
 - conda install --yes -c dan_blanchard python-coveralls
 - cat requirements.txt | xargs -n 1 -L 1 -I{} pip install '{}'
before_script:
script: 
 - python continuous_integration/show-python-packages-versions.py
 - bash cognitiveatlas/tests/run_tests.sh $PWD/cognitiveatlas/tests $PWD

